<a href="https://colab.research.google.com/github/ayesha-ai-dev/Alexa-Project/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [2]:
import numpy as np
n = np.zeros((1,2))
n

array([[0., 0.]])

In [3]:
n1 = np.zeros((3,3))
n1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
n2 = np.full((4,8),1)
n2

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [5]:
n3 = np.arange(5,101,5)
n3

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [6]:
n4 = np.arange(1,100)
n4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
n5 = np.random.randint(1,100,5)
n5

array([67, 52, 73,  2, 68])

In [8]:
n5 = np.random.randint(1,100,5)
n5

array([30, 19, 72, 33, 81])

In [9]:
n5 = np.random.randint(50,100,20)
n5

array([82, 90, 87, 99, 71, 79, 81, 86, 77, 86, 71, 88, 52, 55, 72, 68, 88,
       91, 88, 50])

In [10]:
n6 = np.array([[1,2,3],[4,5,6],[7,8,9]])
n6.shape

(3, 3)

In [11]:
n7 = np.array([[10,20,30],[40,50,60],[70,80,90]])
n7

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [12]:
import numpy as np
n1= np.array([10,20,30,40,50,60])
n2= np.array([50,60,70,80,90])
# np.intersect1d(n1, n2)
# np.setdiff1d(n1, n2)
np.setdiff1d(n2, n1)

array([70, 80, 90])

In [14]:
n1= np.array ([20,40])
n2= np.array ([40,60])
n1 + n2

array([ 60, 100])